pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Upload artifacts'){
            steps{
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: 'http://172.23.109.39:8081',
                    groupId: 'com.mycompany.app',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: 'jenkins',
                    credentialsId: 'nexus_login',
                    artifacts: [
                        [artifactId: 'my-app',
                         classifier: '',
                         file: 'target/my-app-1.0-SNAPSHOT.jar',
                         type: 'jar']
        ]
     )
            }
        }
    }
}
