apiVersion: v1
kind: Pod
metadata:
  name: jenkins-maven-slave
  labels:
    jenkins: slave
spec:
  containers:
  - name: maven
    image: maven:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"